### ISSUE TITLE
Charm hangs on startup

### ISSUE THREAD

**Issue by giucam** [KDAB/Charm#258]
The first time i open charm it creates the config file in ~/.config/KDAB/Charm.conf. If then i close it by hitting ctrl-c in the terminal i opened it in, i cannot start it anymore, as it hangs on startup. This is the backtrace, nothing notable:

```
(gdb) t a a bt

Thread 2 (Thread 0x7fffec4d9700 (LWP 10955)):
#0  0x00007ffff5a2718d in poll () from /usr/lib/libc.so.6
#1  0x00007ffff783dae2 in ?? () from /usr/lib/libxcb.so.1
#2  0x00007ffff783f757 in xcb_wait_for_event () from /usr/lib/libxcb.so.1
#3  0x00007fffeec59379 in ?? () from /usr/lib/libQt5XcbQpa.so.5
#4  0x00007ffff6627b8e in ?? () from /usr/lib/libQt5Core.so.5
#5  0x00007ffff57304a4 in start_thread () from /usr/lib/libpthread.so.0
#6  0x00007ffff5a3013d in clone () from /usr/lib/libc.so.6

Thread 1 (Thread 0x7fffeeebf7c0 (LWP 10890)):
#0  0x00007ffff5a2718d in poll () from /usr/lib/libc.so.6
#1  0x00007ffff42abfbc in ?? () from /usr/lib/libglib-2.0.so.0
#2  0x00007ffff42ac0cc in g_main_context_iteration () from /usr/lib/libglib-2.0.so.0
#3  0x00007ffff685f56b in QEventDispatcherGlib::processEvents(QFlags<QEventLoop::ProcessEventsFlag>) () from /usr/lib/libQt5Core.so.5
#4  0x00007ffff680657a in QEventLoop::exec(QFlags<QEventLoop::ProcessEventsFlag>) () from /usr/lib/libQt5Core.so.5
#5  0x00007ffff680e53c in QCoreApplication::exec() () from /usr/lib/libQt5Core.so.5
#6  0x000000000041cfe6 in main ()
```

If i then remove the config file it starts up again.

However, if i close it by pressing "quit' in the ui, then it works fine, and i can close it with ctrl-c in successive runs without it getting stuck.

**Comment by frankosterfeld** [comment]
@giucam: Which Charm version are you using?

**Comment by giucam** [comment]
Sorry, i forgot to write it. I just built it from master.

**Comment by frankosterfeld** [comment]
Is there a tray icon? Maybe all three windows are just hidden (there were some changes when it comes to window handling). I'd try with Charm 1.10.0 if you need it for work.
