### ISSUE TITLE
Idle detection crashes the app on Wayland

### ISSUE THREAD

**Issue by Pointedstick** [KDAB/Charm#363]
Reduced backtrace:
```
Thread 1 "charmtimetracker" received signal SIGSEGV, Segmentation fault.
0x000000000045f7ad in X11IdleDetector::checkIdleness (this=0x9e5520)
    at /home/nate/kde/src/charm/Charm/Idle/X11IdleDetector.cpp:61
61          const int idleSecs = info->ms_since_user_input / 1000;
Missing separate debuginfos, use: zypper install Mesa-libEGL1-debuginfo-20.3.4-272.5.x86_64
(gdb) bt
#0  0x000000000045f7ad in X11IdleDetector::checkIdleness() (this=0x9e5520)
    at /home/nate/kde/src/charm/Charm/Idle/X11IdleDetector.cpp:61
#1  0x00007ffff6b89946 in QtPrivate::QSlotObjectBase::call(QObject*, void**)
    (a=0x7fffffffd210, r=0x9e5520, this=0xa42ab0)
    at ../../include/QtCore/../../src/corelib/kernel/qobjectdefs_impl.h:398
#2  doActivate<false>(QObject*, int, void**)
    (sender=0x9e5548, signal_index=3, argv=argv@entry=0x7fffffffd210) at kernel/qobject.cpp:3886
```

Clearly `X11IdleDetector` is not going to work on Wayland. :)

**Comment by frankosterfeld** [comment]
Which version are you using? A crash like this has been fixed in commit fe99a1380757d03a40952bc3ff532deb1377d5b4

**Comment by Pointedstick** [comment]
I'm building it from git master, so I guess that fix didn't work for me. :(

**Comment by bam80** [comment]
Isn't it another crash? #364
Need to check on KWin yet.
