### ISSUE TITLE
crash on start: The Wayland connection experienced a fatal error: Protocol error

### ISSUE THREAD

**Issue by bam80** [KDAB/Charm#364]
Latest master, Fedora 33, Gnome Wayland:
```gdb
Program terminated with signal SIGABRT, Aborted.
#0  0x00007fd68a8ca9d5 in raise () from /lib64/libc.so.6
[Current thread is 1 (Thread 0x7fd68777a940 (LWP 362635))]
(gdb) bt
#0  0x00007fd68a8ca9d5 in raise () at /lib64/libc.so.6
#1  0x00007fd68a8b38a4 in abort () at /lib64/libc.so.6
#2  0x00007fd68ae5448f in qt_message_output(QtMsgType, QMessageLogContext const&, QString const&) [clone .cold] () at /lib64/libQt5Core.so.5
#3  0x00007fd686f9ced4 in  () at /lib64/libQt5WaylandClient.so.5
#4  0x00007fd686f9d0ea in QtWaylandClient::QWaylandDisplay::flushRequests() ()
    at /lib64/libQt5WaylandClient.so.5
#5  0x00007fd68b0543c0 in void doActivate<false>(QObject*, int, void**) ()
    at /lib64/libQt5Core.so.5
#6  0x00007fd68b05777a in QSocketNotifier::activated(QSocketDescriptor, QSocketNotifier::Type, QSocketNotifier::QPrivateSignal) () at /lib64/libQt5Core.so.5
#7  0x00007fd68b057f21 in QSocketNotifier::event(QEvent*) ()
    at /lib64/libQt5Core.so.5
#8  0x00007fd68bb43ec3 in QApplicationPrivate::notify_helper(QObject*, QEvent*)
    () at /lib64/libQt5Widgets.so.5
#9  0x00007fd68b024bd8 in QCoreApplication::notifyInternal2(QObject*, QEvent*)
    () at /lib64/libQt5Core.so.5
#10 0x00007fd68b072157 in socketNotifierSourceDispatch(_GSource*, int (*)(void*), void*) () at /lib64/libQt5Core.so.5
#11 0x00007fd68a38c96f in g_main_context_dispatch () at /lib64/libglib-2.0.so.0
#12 0x00007fd68a3de758 in g_main_context_iterate.constprop ()
    at /lib64/libglib-2.0.so.0
#13 0x00007fd68a389d43 in g_main_context_iteration ()
--Type <RET> for more, q to quit, c to continue without paging--
    at /lib64/libglib-2.0.so.0
#14 0x00007fd68b0716f3 in QEventDispatcherGlib::processEvents(QFlags<QEventLoop::ProcessEventsFlag>) () at /lib64/libQt5Core.so.5
#15 0x00007fd68b02357b in QEventLoop::exec(QFlags<QEventLoop::ProcessEventsFlag>) () at /lib64/libQt5Core.so.5
#16 0x00007fd68b02b1b4 in QCoreApplication::exec() () at /lib64/libQt5Core.so.5
#17 0x000000000042c0c9 in main ()

**Comment by bam80** [comment]
The bug reproduces very reliably on my system, but after 3-4 attempt in row it might still start

**Comment by frankosterfeld** [comment]
Hmm, I've tested some Wayland issues (but nothing like this) under Fedora 33/Gnome recently, didn't see this. Which Qt version are you using?

**Comment by bam80** [comment]
Yes it's default Qt from Fedora, qt5-qtbase-common-5.15.2-2.fc33.noarch.

WAYLAND_DEBUG log:
```
$ WAYLAND_DEBUG=1 ./charmtimetracker 
[4106971.090]  -> wl_display@1.get_registry(new id wl_registry@2)
[4106972.713]  -> wl_display@1.sync(new id wl_callback@3)
[4106973.604] wl_display@1.delete_id(3)
[4106973.986] wl_registry@2.global(1, "wl_drm", 2)
[4106974.165] wl_registry@2.global(2, "wl_compositor", 4)
[4106974.610]  -> wl_registry@2.bind(2, "wl_compositor", 3, new id [unknown]@4)
[4106974.896] wl_registry@2.global(3, "wl_shm", 1)
[4106975.069]  -> wl_registry@2.bind(3, "wl_shm", 1, new id [unknown]@5)
[4106975.270] wl_registry@2.global(4, "wl_output", 2)
[4106975.481]  -> wl_registry@2.bind(4, "wl_output", 2, new id [unknown]@6)
[4106975.774] wl_registry@2.global(5, "zxdg_output_manager_v1", 3)
[4106976.209]  -> wl_registry@2.bind(5, "zxdg_output_manager_v1", 3, new id [unknown]@7)
[4106976.568]  -> zxdg_output_manager_v1@7.get_xdg_output(new id zxdg_output_v1@8, wl_output@6)
[4106976.665]  -> wl_display@1.sync(new id wl_callback@9)
[4106976.881] wl_registry@2.global(6, "wl_data_device_manager", 3)
[4106976.993]  -> wl_registry@2.bind(6, "wl_data_device_manager", 1, new id [unknown]@10)
[4106977.522] wl_registry@2.global(7, "zwp_primary_selection_device_manager_v1", 1)
[4106977.633]  -> wl_registry@2.bind(7, "zwp_primary_selection_device_manager_v1", 1, new id [unknown]@11)
[4106977.950] wl_registry@2.global(8, "gtk_primary_selection_device_manager", 1)
[4106978.034] wl_registry@2.global(9, "wl_subcompositor", 1)
[4106978.378]  -> wl_registry@2.bind(9, "wl_subcompositor", 1, new id [unknown]@12)
[4106978.431] wl_registry@2.global(10, "xdg_wm_base", 3)
[4106978.541] wl_registry@2.global(11, "zxdg_shell_v6", 1)
[4106978.598] wl_registry@2.global(12, "wl_shell", 1)
[4106978.642] wl_registry@2.global(13, "gtk_shell1", 3)
[4106978.724] wl_registry@2.global(14, "wp_viewporter", 1)
[4106978.805] wl_registry@2.global(15, "zwp_pointer_gestures_v1", 1)
[4106978.849] wl_registry@2.global(16, "zwp_tablet_manager_v2", 1)
[4106978.894]  -> wl_registry@2.bind(16, "zwp_tablet_manager_v2", 1, new id [unknown]@13)
[4106978.950] wl_registry@2.global(17, "wl_seat", 5)
[4106979.027]  -> wl_registry@2.bind(17, "wl_seat", 5, new id [unknown]@14)
[4106979.444]  -> wl_data_device_manager@10.get_data_device(new id wl_data_device@15, wl_seat@14)
[4106979.485]  -> zwp_primary_selection_device_manager_v1@11.get_device(new id zwp_primary_selection_device_v1@16, wl_seat@14)
[4106979.579]  -> zwp_tablet_manager_v2@13.get_tablet_seat(new id zwp_tablet_seat_v2@17, wl_seat@14)
[4106979.666] wl_registry@2.global(18, "zwp_relative_pointer_manager_v1", 1)
[4106979.714] wl_registry@2.global(19, "zwp_pointer_constraints_v1", 1)
[4106979.759] wl_registry@2.global(20, "zxdg_exporter_v1", 1)
[4106979.802] wl_registry@2.global(21, "zxdg_importer_v1", 1)
[4106979.861] wl_registry@2.global(22, "zwp_linux_dmabuf_v1", 3)
[4106979.950] wl_registry@2.global(23, "zwp_keyboard_shortcuts_inhibit_manager_v1", 1)
[4106979.994] wl_registry@2.global(24, "zwp_text_input_manager_v3", 1)
[4106980.047] wl_registry@2.global(25, "gtk_text_input_manager", 1)
[4106980.091] wl_callback@3.done(144852)
[4106980.855] wl_display@1.delete_id(9)
[4106980.905] wl_shm@5.format(0)
[4106980.961] wl_shm@5.format(1)
[4106981.033] wl_shm@5.format(909199186)
[4106981.090] wl_shm@5.format(808669761)
[4106981.143] wl_shm@5.format(808669784)
[4106981.278] wl_shm@5.format(808665665)
[4106981.302] wl_shm@5.format(808665688)
[4106981.319] wl_shm@5.format(1211388481)
[4106981.428] wl_shm@5.format(1211388504)
[4106981.449] wl_shm@5.format(1211384385)
[4106981.469] wl_shm@5.format(1211384408)
[4106981.586] wl_output@6.geometry(0, 0, 380, 300, 0, "NEC", "LCD1970GX", 0)
[4106982.053] wl_output@6.mode(3, 1280, 1024, 60020)
[4106982.111] wl_output@6.scale(1)
[4106982.267] wl_output@6.done()
[4106986.115] zxdg_output_v1@8.logical_position(0, 0)
[4106988.042] zxdg_output_v1@8.logical_size(1280, 1024)
[4106988.608] zxdg_output_v1@8.name("HDMI-1")
[4106988.998] zxdg_output_v1@8.description("NEC Corporation 19"")
[4106989.389] wl_output@6.done()
[4106989.690] wl_callback@9.done(144852)
[4106990.054] wl_seat@14.capabilities(3)
[4106990.455]  -> wl_seat@14.get_keyboard(new id wl_keyboard@9)
[4106990.925]  -> wl_seat@14.get_pointer(new id wl_pointer@3)
[4106992.137] wl_seat@14.name("seat0")
[4107065.082]  -> wl_display@1.get_registry(new id wl_registry@2)
[4107065.142]  -> wl_display@1.sync(new id wl_callback@3)
[4107069.342] wl_display@1.delete_id(3)
[4107069.645] wl_registry@2.global(1, "wl_drm", 2)
[4107069.959] wl_registry@2.global(2, "wl_compositor", 4)
[4107070.239]  -> wl_registry@2.bind(2, "wl_compositor", 3, new id [unknown]@4)
[4107070.968] wl_registry@2.global(3, "wl_shm", 1)
[4107071.739]  -> wl_registry@2.bind(3, "wl_shm", 1, new id [unknown]@5)
[4107075.565]  -> wl_shm@5.create_pool(new id wl_shm_pool@6, fd 12, 2304)
[4107086.959]  -> wl_shm_pool@6.resize(5568)
[4107087.259]  -> wl_shm_pool@6.resize(12096)
[4107087.349] wl_registry@2.global(4, "wl_output", 2)
[4107087.391]  -> wl_registry@2.bind(4, "wl_output", 2, new id [unknown]@7)
[4107087.656]  -> wl_display@1.sync(new id wl_callback@8)
[4107087.707] wl_registry@2.global(5, "zxdg_output_manager_v1", 3)
[4107087.757]  -> wl_registry@2.bind(5, "zxdg_output_manager_v1", 3, new id [unknown]@9)
[4107087.814]  -> zxdg_output_manager_v1@9.get_xdg_output(new id zxdg_output_v1@10, wl_output@7)
[4107087.854]  -> wl_display@1.sync(new id wl_callback@11)
[4107087.883] wl_registry@2.global(6, "wl_data_device_manager", 3)
[4107087.936]  -> wl_registry@2.bind(6, "wl_data_device_manager", 3, new id [unknown]@12)
[4107087.997] wl_registry@2.global(7, "zwp_primary_selection_device_manager_v1", 1)
[4107088.073]  -> wl_registry@2.bind(7, "zwp_primary_selection_device_manager_v1", 1, new id [unknown]@13)
[4107088.133] wl_registry@2.global(8, "gtk_primary_selection_device_manager", 1)
[4107088.183]  -> wl_registry@2.bind(8, "gtk_primary_selection_device_manager", 1, new id [unknown]@14)
[4107088.246] wl_registry@2.global(9, "wl_subcompositor", 1)
[4107088.292]  -> wl_registry@2.bind(9, "wl_subcompositor", 1, new id [unknown]@15)
[4107088.556] wl_registry@2.global(10, "xdg_wm_base", 3)
[4107088.600] wl_registry@2.global(11, "zxdg_shell_v6", 1)
[4107088.643] wl_registry@2.global(12, "wl_shell", 1)
[4107088.686] wl_registry@2.global(13, "gtk_shell1", 3)
[4107088.907]  -> wl_registry@2.bind(13, "gtk_shell1", 3, new id [unknown]@16)
[4107088.969] wl_registry@2.global(14, "wp_viewporter", 1)
[4107089.134] wl_registry@2.global(15, "zwp_pointer_gestures_v1", 1)
[4107089.248]  -> wl_registry@2.bind(15, "zwp_pointer_gestures_v1", 1, new id [unknown]@17)
[4107089.317] wl_registry@2.global(16, "zwp_tablet_manager_v2", 1)
[4107089.358]  -> wl_registry@2.bind(16, "zwp_tablet_manager_v2", 1, new id [unknown]@18)
[4107089.513] wl_registry@2.global(17, "wl_seat", 5)
[4107091.878]  -> wl_registry@2.bind(17, "wl_seat", 5, new id [unknown]@19)
[4107118.164]  -> wl_compositor@4.create_surface(new id wl_surface@20)
[4107118.627]  -> zwp_primary_selection_device_manager_v1@13.get_device(new id zwp_primary_selection_device_v1@21, wl_seat@19)
[4107119.062]  -> wl_data_device_manager@12.get_data_device(new id wl_data_device@22, wl_seat@19)
[4107120.411]  -> wl_compositor@4.create_surface(new id wl_surface@23)
[4107120.775]  -> zwp_tablet_manager_v2@18.get_tablet_seat(new id zwp_tablet_seat_v2@24, wl_seat@19)
[4107121.210]  -> wl_display@1.sync(new id wl_callback@25)
[4107121.585] wl_registry@2.global(18, "zwp_relative_pointer_manager_v1", 1)
[4107122.192] wl_registry@2.global(19, "zwp_pointer_constraints_v1", 1)
[4107122.789] wl_registry@2.global(20, "zxdg_exporter_v1", 1)
[4107123.392]  -> wl_registry@2.bind(20, "zxdg_exporter_v1", 1, new id [unknown]@26)
[4107124.000] wl_registry@2.global(21, "zxdg_importer_v1", 1)
[4107124.451]  -> wl_registry@2.bind(21, "zxdg_importer_v1", 1, new id [unknown]@27)
[4107126.215] wl_registry@2.global(22, "zwp_linux_dmabuf_v1", 3)
[4107126.919] wl_registry@2.global(23, "zwp_keyboard_shortcuts_inhibit_manager_v1", 1)
[4107127.426]  -> wl_registry@2.bind(23, "zwp_keyboard_shortcuts_inhibit_manager_v1", 1, new id [unknown]@28)
[4107129.111] wl_registry@2.global(24, "zwp_text_input_manager_v3", 1)
[4107129.243] wl_registry@2.global(25, "gtk_text_input_manager", 1)
[4107129.351] wl_callback@3.done(144852)
[4107130.535] wl_display@1.delete_id(8)
[4107130.622] wl_display@1.delete_id(11)
[4107130.677] wl_display@1.delete_id(25)
[4107130.731] wl_shm@5.format(0)
[4107130.784] wl_shm@5.format(1)
[4107130.837] wl_shm@5.format(909199186)
[4107130.891] wl_shm@5.format(808669761)
[4107130.944] wl_shm@5.format(808669784)
[4107130.998] wl_shm@5.format(808665665)
[4107131.064] wl_shm@5.format(808665688)
[4107131.118] wl_shm@5.format(1211388481)
[4107131.172] wl_shm@5.format(1211388504)
[4107131.229] wl_shm@5.format(1211384385)
[4107131.282] wl_shm@5.format(1211384408)
[4107131.335] wl_output@7.geometry(0, 0, 380, 300, 0, "NEC", "LCD1970GX", 0)
[4107131.590] wl_output@7.mode(3, 1280, 1024, 60020)
[4107131.726] wl_output@7.scale(1)
[4107131.781] wl_output@7.done()
[4107131.852] wl_callback@8.done(144852)
[4107131.913] zxdg_output_v1@10.logical_position(0, 0)
[4107135.575] zxdg_output_v1@10.logical_size(1280, 1024)
[4107135.762] zxdg_output_v1@10.name("HDMI-1")
[4107135.830] zxdg_output_v1@10.description("NEC Corporation 19"")
[4107135.887] wl_output@7.done()
[4107135.978] wl_callback@11.done(144852)
[4107136.076] gtk_shell1@16.capabilities(0)
[4107136.174] wl_seat@19.capabilities(3)
[4107136.246]  -> wl_seat@19.get_pointer(new id wl_pointer@11)
[4107136.406]  -> zwp_pointer_gestures_v1@17.get_swipe_gesture(new id zwp_pointer_gesture_swipe_v1@8, wl_pointer@11)
[4107137.703]  -> zwp_pointer_gestures_v1@17.get_pinch_gesture(new id zwp_pointer_gesture_pinch_v1@3, wl_pointer@11)
[4107137.818]  -> wl_seat@19.get_keyboard(new id wl_keyboard@29)
[4107137.953] wl_seat@19.name("seat0")
[4107138.031] wl_callback@25.done(144852)
[4107138.094]  -> wl_registry@2.bind(10, "xdg_wm_base", 1, new id [unknown]@25)
[4107411.740]  -> wl_display@1.get_registry(new id wl_registry@18)
[4107411.873]  -> wl_display@1.sync(new id wl_callback@19)
[4107412.754] wl_display@1.delete_id(19)
[4107413.598] wl_registry@18.global(1, "wl_drm", 2)
[4107415.124]  -> wl_registry@18.bind(1, "wl_drm", 2, new id [unknown]@20)
[4107417.340] wl_registry@18.global(2, "wl_compositor", 4)
[4107418.510] wl_registry@18.global(3, "wl_shm", 1)
[4107419.795] wl_registry@18.global(4, "wl_output", 2)
[4107420.190] wl_registry@18.global(5, "zxdg_output_manager_v1", 3)
[4107420.270] wl_registry@18.global(6, "wl_data_device_manager", 3)
[4107420.391] wl_registry@18.global(7, "zwp_primary_selection_device_manager_v1", 1)
[4107420.496] wl_registry@18.global(8, "gtk_primary_selection_device_manager", 1)
[4107420.614] wl_registry@18.global(9, "wl_subcompositor", 1)
[4107420.734] wl_registry@18.global(10, "xdg_wm_base", 3)
[4107420.838] wl_registry@18.global(11, "zxdg_shell_v6", 1)
[4107420.953] wl_registry@18.global(12, "wl_shell", 1)
[4107421.083] wl_registry@18.global(13, "gtk_shell1", 3)
[4107421.292] wl_registry@18.global(14, "wp_viewporter", 1)
[4107421.408] wl_registry@18.global(15, "zwp_pointer_gestures_v1", 1)
[4107421.513] wl_registry@18.global(16, "zwp_tablet_manager_v2", 1)
[4107421.632] wl_registry@18.global(17, "wl_seat", 5)
[4107421.745] wl_registry@18.global(18, "zwp_relative_pointer_manager_v1", 1)
[4107421.849] wl_registry@18.global(19, "zwp_pointer_constraints_v1", 1)
[4107421.968] wl_registry@18.global(20, "zxdg_exporter_v1", 1)
[4107422.098] wl_registry@18.global(21, "zxdg_importer_v1", 1)
[4107422.213] wl_registry@18.global(22, "zwp_linux_dmabuf_v1", 3)
[4107422.323]  -> wl_registry@18.bind(22, "zwp_linux_dmabuf_v1", 3, new id [unknown]@21)
[4107422.482] wl_registry@18.global(23, "zwp_keyboard_shortcuts_inhibit_manager_v1", 1)
[4107422.586] wl_registry@18.global(24, "zwp_text_input_manager_v3", 1)
[4107422.688] wl_registry@18.global(25, "gtk_text_input_manager", 1)
[4107422.794] wl_callback@19.done(144852)
[4107422.855]  -> wl_display@1.sync(new id wl_callback@19)
[4107425.933] wl_display@1.delete_id(19)
[4107426.447] wl_drm@20.device("/dev/dri/card0")
[4107428.988]  -> wl_drm@20.authenticate(2)
[4107429.291] wl_drm@20.format(875713089)
[4107430.576] wl_drm@20.format(875713112)
[4107430.970] wl_drm@20.format(909199186)
[4107431.357] wl_drm@20.format(961959257)
[4107431.730] wl_drm@20.format(825316697)
[4107432.120] wl_drm@20.format(842093913)
[4107432.643] wl_drm@20.format(909202777)
[4107434.001] wl_drm@20.format(875713881)
[4107434.048] wl_drm@20.format(842094158)
[4107434.089] wl_drm@20.format(909203022)
[4107434.144] wl_drm@20.format(1448695129)
[4107434.213] wl_drm@20.capabilities(1)
[4107434.295] zwp_linux_dmabuf_v1@21.format(875713089)
[4107434.320] zwp_linux_dmabuf_v1@21.modifier(875713089, 16777215, 4294967295)
[4107434.364] zwp_linux_dmabuf_v1@21.format(875713112)
[4107434.388] zwp_linux_dmabuf_v1@21.modifier(875713112, 16777215, 4294967295)
[4107434.485] zwp_linux_dmabuf_v1@21.format(808669761)
[4107434.583] zwp_linux_dmabuf_v1@21.modifier(808669761, 16777215, 4294967295)
[4107434.760] zwp_linux_dmabuf_v1@21.format(808669784)
[4107434.807] zwp_linux_dmabuf_v1@21.modifier(808669784, 16777215, 4294967295)
[4107434.851] zwp_linux_dmabuf_v1@21.format(909199186)
[4107434.894] zwp_linux_dmabuf_v1@21.modifier(909199186, 16777215, 4294967295)
[4107434.922] zwp_linux_dmabuf_v1@21.format(1211384385)
[4107434.938] zwp_linux_dmabuf_v1@21.modifier(1211384385, 16777215, 4294967295)
[4107434.989] zwp_linux_dmabuf_v1@21.format(1211384408)
[4107435.048] zwp_linux_dmabuf_v1@21.modifier(1211384408, 16777215, 4294967295)
[4107435.155] zwp_linux_dmabuf_v1@21.format(1211388504)
[4107435.220] zwp_linux_dmabuf_v1@21.modifier(1211388504, 16777215, 4294967295)
[4107435.266] zwp_linux_dmabuf_v1@21.format(1211388481)
[4107435.311] zwp_linux_dmabuf_v1@21.modifier(1211388481, 16777215, 4294967295)
[4107435.357] wl_callback@19.done(144852)
[4107435.445]  -> wl_display@1.sync(new id wl_callback@19)
[4107436.175] wl_display@1.delete_id(19)
[4107436.207] wl_drm@20.authenticated()
[4107436.220] wl_callback@19.done(144852)
[4107490.862]  -> wl_compositor@4.create_surface(new id wl_surface@19)
[4107495.715]  -> wl_registry@2.bind(10, "xdg_wm_base", 1, new id [unknown]@22)
[4107496.228]  -> xdg_wm_base@22.get_xdg_surface(new id xdg_surface@23, wl_surface@19)
[4107496.486]  -> xdg_surface@23.get_toplevel(new id xdg_toplevel@24)
[4107496.524]  -> xdg_toplevel@24.set_title("Time Tracker")
[4107496.571]  -> xdg_toplevel@24.set_app_id("com.kdab.charmtimetracker")
[4107496.596]  -> wl_surface@19.set_buffer_scale(1)
[4107498.630]  -> wl_surface@19.set_buffer_transform(0)
[4107498.678]  -> wl_surface@19.commit()
[4107498.700] wl_keyboard@9.keymap(1, fd 22, 53899)
[4107505.111] wl_keyboard@9.repeat_info(33, 500)
[4107515.159]  -> xdg_surface@23.set_window_geometry(0, 0, 618, 220)
[4107517.392]  -> wl_compositor@4.create_region(new id wl_region@25)
[4107521.125]  -> wl_region@25.add(238, 614, 612, 187)
[4107521.193]  -> wl_surface@19.set_opaque_region(wl_region@25)
[4107521.246]  -> wl_region@25.destroy()
[4107543.271] xdg_toplevel@24.configure(0, 0, array)
[4107551.987] xdg_surface@23.configure(3326)
[4107552.827]  -> xdg_surface@23.set_window_geometry(0, 0, 618, 220)
[4107554.215]  -> xdg_toplevel@24.set_min_size(388, 187)
[4107555.009]  -> xdg_toplevel@24.set_max_size(0, 187)
[4107555.813]  -> xdg_surface@23.ack_configure(3326)
[4107560.075]  -> wl_shm@5.create_pool(new id wl_shm_pool@26, fd 26, 543840)
[4107561.475]  -> wl_shm_pool@26.create_buffer(new id wl_buffer@27, 0, 618, 220, 2472, 0)
[4107578.896]  -> wl_surface@19.damage(0, 0, 624, 30)
[4107580.438]  -> wl_surface@19.damage(0, 30, 3, 220)
[4107581.751]  -> wl_surface@19.damage(621, 30, 3, 220)
[4107583.030]  -> wl_surface@19.damage(0, 250, 624, 3)
[4107587.096]  -> wl_surface@19.frame(new id wl_callback@28)
[4107587.900]  -> wl_surface@19.attach(wl_buffer@27, 0, 0)
[4107589.140]  -> wl_surface@19.damage(3, 30, 612, 187)
[4107590.344]  -> wl_surface@19.commit()
[4107597.537]  -> wl_shm@5.create_pool(new id wl_shm_pool@29, fd 26, 543840)
[4107598.810]  -> wl_shm_pool@29.create_buffer(new id wl_buffer@30, 0, 618, 220, 2472, 0)
[4107604.397]  -> wl_surface@19.frame(new id wl_callback@31)
[4107605.198]  -> wl_surface@19.attach(wl_buffer@30, 0, 0)
[4107606.176]  -> wl_surface@19.damage(3, 30, 612, 187)
[4107607.546]  -> wl_surface@19.commit()
[4107820.461] wl_display@1.delete_id(25)
[4107820.585] wl_display@1.delete_id(28)
[4107820.644] wl_buffer@27.release()
[4107820.687] xdg_toplevel@24.configure(618, 187, array)
[4107820.796] xdg_surface@23.configure(3327)
[4107820.875] xdg_toplevel@24.configure(618, 187, array)
[4107820.988] xdg_surface@23.configure(3329)
[4107821.155] wl_keyboard@9.modifiers(144854, 0, 0, 0, 0)
[4107821.322] wl_keyboard@9.enter(144854, wl_surface@19, array)
[4107821.446] wl_data_device@15.data_offer(new id wl_data_offer@43454704)
[4107821.524] wl_data_offer@4278190080.offer("text/plain;charset=utf-8")
[4107821.589] wl_data_device@15.selection(wl_data_offer@4278190080)
[4107821.654] zwp_primary_selection_device_v1@16.data_offer(new id zwp_primary_selection_offer_v1@43455280)
[4107821.731] zwp_primary_selection_offer_v1@4278190081.offer("text/plain;charset=utf-8")
[4107821.790] zwp_primary_selection_offer_v1@4278190081.offer("text/plain")
[4107821.848] zwp_primary_selection_offer_v1@4278190081.offer("UTF8_STRING")
[4107821.907] zwp_primary_selection_offer_v1@4278190081.offer("TEXT")
[4107821.963] zwp_primary_selection_offer_v1@4278190081.offer("STRING")
[4107822.031] zwp_primary_selection_offer_v1@4278190081.offer("MULTIPLE")
[4107822.090] zwp_primary_selection_offer_v1@4278190081.offer("SAVE_TARGETS")
[4107822.149] zwp_primary_selection_offer_v1@4278190081.offer("TARGETS")
[4107822.205] zwp_primary_selection_offer_v1@4278190081.offer("TIMESTAMP")
[4107822.264] zwp_primary_selection_device_v1@16.selection(zwp_primary_selection_offer_v1@4278190081)
[4107822.323] wl_surface@19.enter(wl_output@6)
[4107824.342]  -> xdg_toplevel@24.set_min_size(388, 206)
[4107824.481]  -> xdg_toplevel@24.set_max_size(0, 187)
[4107824.566]  -> wl_surface@19.commit()
[4107824.643]  -> xdg_surface@23.set_window_geometry(0, 0, 618, 239)
[4107824.798]  -> wl_compositor@4.create_region(new id wl_region@28)
[4107824.873]  -> wl_region@28.add(238, 614, 612, 206)
[4107825.010]  -> wl_surface@19.set_opaque_region(wl_region@28)
[4107825.087]  -> wl_region@28.destroy()
[4107828.369]  -> wl_display@1.sync(new id wl_callback@25)
[4107828.521]  -> xdg_surface@23.set_window_geometry(0, 0, 618, 239)
[4107829.475]  -> wl_compositor@4.create_region(new id wl_region@32)
[4107830.011]  -> wl_region@32.add(238, 614, 612, 154)
[4107830.561]  -> wl_surface@19.set_opaque_region(wl_region@32)
[4107830.834]  -> wl_region@32.destroy()
[4107831.123]  -> xdg_toplevel@24.set_min_size(388, 206)
[4107831.296]  -> xdg_toplevel@24.set_max_size(0, 187)
[4107831.595]  -> xdg_surface@23.ack_configure(3329)
[4107832.297]  -> wl_shm_pool@26.destroy()
[4107832.405]  -> wl_buffer@27.destroy()
[4107832.848]  -> wl_shm@5.create_pool(new id wl_shm_pool@33, fd 26, 590808)
[4107833.709]  -> wl_shm_pool@33.create_buffer(new id wl_buffer@34, 0, 618, 239, 2472, 0)
[4107846.727]  -> wl_surface@19.damage(0, 0, 624, 30)
[4107847.249]  -> wl_surface@19.damage(0, 30, 3, 239)
[4107847.973]  -> wl_surface@19.damage(621, 30, 3, 239)
[4107848.538]  -> wl_surface@19.damage(0, 269, 624, 3)
[4107849.325]  -> wl_surface@19.frame(new id wl_callback@35)
[4107849.664]  -> wl_surface@19.attach(wl_buffer@34, 0, 0)
[4107850.117]  -> wl_surface@19.damage(3, 30, 612, 206)
[4107851.380]  -> wl_surface@19.commit()
[4107856.424] wl_buffer@30.release()
[4107857.209]  -> xdg_toplevel@24.set_min_size(388, 206)
[4107857.686]  -> xdg_toplevel@24.set_max_size(0, 206)
[4107857.913]  -> wl_surface@19.commit()
[4107859.994]  -> wl_shm_pool@29.destroy()
[4107860.255]  -> wl_buffer@30.destroy()
[4107860.645]  -> wl_shm@5.create_pool(new id wl_shm_pool@36, fd 26, 590808)
[4107861.229]  -> wl_shm_pool@36.create_buffer(new id wl_buffer@37, 0, 618, 239, 2472, 0)
[4107864.186]  -> wl_surface@19.frame(new id wl_callback@38)
[4107864.636]  -> wl_surface@19.attach(wl_buffer@37, 0, 0)
[4107865.140]  -> wl_surface@19.damage(3, 30, 612, 19)
[4107865.700]  -> wl_surface@19.commit()
[4107901.187] wl_display@1.delete_id(31)
[4107901.255] wl_display@1.error(wl_surface@19, 4, "Invalid min/max size")
The Wayland connection experienced a fatal error: Protocol error
Aborted (core dumped)

**Comment by davidedmundson** [comment]
>[4107857.686]  -> xdg_toplevel@24.set_max_size(0, 206)

Yeah, that's not a valid max size, Mutter is in the right - probably could be worked round here in charm, but we should fix that in the QtQPA

**Comment by bam80** [comment]
I'll check on KWin too when I get a chance

**Comment by bam80** [comment]
Filed an upstream bug:
https://bugreports.qt.io/browse/QTBUG-103391
